### ISSUE TITLE
Tempo dashboard

### ISSUE THREAD

**Issue by fguillen** [michal-kazmierczak/opentelemetry-rails-example#3]
I am configuring my architecture observability strongly inspired by this repo. 

I want to configure a Tempo dashboard, but I don't know where to start. There are [not any usable Tempo dashboards on the Grafana Dashboards page](https://grafana.com/grafana/dashboards/?dataSource=tempo).

In this repo, I see there is [one Dashboard](https://github.com/michal-kazmierczak/opentelemetry-rails-example/blob/main/volumes/grafana/provisioning/dashboards/general/rack-api-performance.json), but it is a Prometheus one.

Thanks for your work

**Comment by michal-kazmierczak** [comment]
Hello @fguillen 

Typically, Tempo (tracing) doesn't have dedicated dashboards like Prometheus (metrics). Instead, it's designed to work seamlessly in the Grafana's Explore mode. This allows you to search and visualize traces without the need for pre-configured dashboards.

That's probably why there are not Tempo dashboards out there.

Are there any particular features you lack in the Explore mode while using Tempo as the data source?

**Comment by fguillen** [comment]
Hi @michal-kazmierczak 

> Are there any particular features you lack in the Explore mode while using Tempo as the data source?

The Explore mode has my logs there and "Logs Volume," but I can not save my configuration and give it a name, as in a Dashboard. If I use the "Add to Dashboard" button, it creates a "Logs" panel but not the "Logs Volume" (it is [not supported in custom dashboards](https://github.com/grafana/grafana/discussions/46600))

I would also like to have some buttons to filter by level: "debug," "info," "error.".

In general, I don't know what kind of Dashboard I can do with the logs. Mostly looking for what other people do

**Comment by fguillen** [comment]
Mi configuration and logs format was different, after small reconfiguration and managed to make your dashboard to work with my format: 

- https://gist.github.com/fguillen/92b4f83c5b7e7ae256519fcb15783e35

Thanks again
