### ISSUE TITLE
Integrate `influxdb-rails` to instrument the Rails app

### ISSUE THREAD

**Issue by fguillen** [michal-kazmierczak/opentelemetry-rails-example#5]
I am seeing these nice Dashboards specialized in Rails apps:

- https://grafana.com/grafana/dashboards/10428-performance/

With monitors for Jobs, Exceptions, and more

It requires generating metrics with the `influxdb-rails` that specializes in instrumenting rails apps:

- https://github.com/influxdata/influxdb-rails/tree/master

It requires, of course, an InfluxDB instance. 

Do you think this setup adds any value to the setup this project already has?

Or do you think we can achieve the same level of Rails specialized Dashboards with the `prometheus-client` metrics?

**Comment by michal-kazmierczak** [comment]
Thanks for sharing this, @fguillen. I hadn't seen it before.

I see that the dashboard combines the HTTP layer, background jobs, and emails. Personally, I prefer using more specialized, low-level dashboards that are separate for HTTP and background jobs. The absolute minimum I always include is RED (Rate, Errors, Durations) dashboards for both the HTTP server and the background processing server (typically Sidekiq). Any additional dashboards are specific to the application's domain.

However, I'll take this as a prompt to explore InfluxDB and see if it could potentially replace the StatsD and Prometheus setup I've been using.
